apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-rs-secret-pod
  template:
    metadata:
      labels:
        app: mysql-rs-secret-pod
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: credential
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
